In [59]:
##Numpy Arrays offer powerful library for numerical computing in python
##Homogeneous Data Type:NumPy arrays contain elements that are all of the
##Multidimensional:Arrays can have multiple dimensions
##Slicing and Indexing:Advanced slicing and indexing features
##Efficient Memory Usage:NumPy arrays have a fixed size at creation
##NumPy arrays are a foundational tool for scientific computing in python

In [61]:
import numpy as np

In [63]:
#dir(np)

In [65]:
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [67]:
x = np.array([45,67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [103]:
x = np.array(["A",67,57,9.8])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '57' '9.8']
<class 'numpy.ndarray'>
<U32


In [105]:
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [107]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [109]:
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [111]:
d = np.array([1.3467, 3.10987,4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [113]:
d = np.array([1.3467, 3.10987,4.91236])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.91236]
[1.16 1.76 2.22]


In [115]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [117]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NaN]])
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [119]:
a2 =np.array([[3,4,6],[7,9,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [121]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
a3

array([[3, 4, 5],
       [7, 2, 8],
       [9, 1, 6]])

In [123]:
a3 = np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [7 2 8]
 [9 1 6]]
[[0 4 5]
 [7 0 8]
 [9 1 0]]


In [125]:
A =np.array([[1,2], [3,4]])
B =np.array([[5,6], [7,8]])

C =np.matmul(A, B)

In [127]:
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [129]:
a4 = np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
a4

array([[ 3,  4,  5],
       [ 7,  2,  8],
       [ 9,  1,  6],
       [10,  9, 18]])

In [131]:
print(np.argmax(a3, axis=1))
print(np.argmax(a3, axis=0))


[2 2 0]
[2 0 1]


In [133]:
print(np.amax(a3, axis =1))
print(np.amax(a3, axis =0))


[5 8 9]
[9 4 8]
